export const AllProducts = [
    { 
        id: '1', 
        title: "Men Shirt 1",
        mainCategory:"fashion", 
        category: "men", 
        type: "shirts",
        imageURL:'/images/fashion-products/shirt1.jpeg' 
    },
    { 
        id: '2', 
        title: "Men Shirt 2", 
        mainCategory:"fashion",
        category: "men", 
        type: "shirts",
        imageURL:'/images/fashion-products/shirt2.jpeg' 
    },
    { 
        id: '3', 
        title: "Men Shirt 3", 
        mainCategory:"fashion",
        category: "men", 
        type: "shirts",
        imageURL:'/images/fashion-products/shirt3.jpeg' 
    },
    { 
        id: '4', 
        title: "Men Pant 1", 
        mainCategory:"fashion",
        category: "men", 
        type: "pants",
        imageURL:'/images/fashion-products/pant1.jpeg' 
    },
    { 
        id: '5', 
        title: "Men Pant 2", 
        mainCategory:"fashion",
        category: "men", 
        type: "pants",
        imageURL:'/images/fashion-products/pant2.jpg' 
    },
    { 
        id: '6', 
        title: "Men pant 3", 
        mainCategory:"fashion",
        category: "men", 
        type: "pants",
        imageURL:'/images/fashion-products/pant3.jpg' 
    },
    { 
        id: '7', 
        title: "Kids Pant 1", 
        mainCategory:"fashion",
        category: "kids", 
        type: "pants",
        imageURL:'/images/fashion-products/kid1.jpeg' 
    },
    { 
        id: '8', 
        title: "Kids Pant 2", 
        mainCategory:"fashion",
        category: "kids", 
        type: "pants",
        imageURL:'/images/fashion-products/kid2.jpeg' 
    },
     { 
        id: '9', 
        title: "Shoe 1", 
        mainCategory:"fashion",
        category: "men", 
        type: "shoes",
        imageURL:'/images/fashion-products/shoe1.jpeg' 
    },
     { 
        id: '10', 
        title: "Shoe 2", 
        mainCategory:"fashion",
        category: "men", 
        type: "shoes",
        imageURL:'/images/fashion-products/shoe2.jpg' 
    },
     { 
        id: '11', 
        title: "Women Kurta 1", 
        mainCategory:"fashion",
        category: "women", 
        type: "kurta",
        imageURL:'/images/fashion-products/women1.jpg' 
    },
     { 
        id: '12', 
        title: "Women Kurta 2", 
        mainCategory:"fashion",
        category: "women", 
        type: "kurta",
        imageURL:'/images/fashion-products/women2.jpg' 
    },

     {
        id:'st1',
        title:'My pencil (Wow) Dollar 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:210,
        imageURL:'/images/stationary-products/my_pencil_dollar.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st2',
        title:'Apple Sharpener',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/apple_sharpener.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st3',
        title:'Board Marker Dollar 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:680,
        imageURL:'/images/stationary-products/board_marker.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st4',
        title:'Cutter',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:305,
        imageURL:'/images/stationary-products/cutter.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st5',
        title:'Deer Color Large 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/stationary-products/deer_color_large.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st6',
        title:'Deer Color Small 12 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:65,
        imageURL:'/images/stationary-products/deer_color_small.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st7',
        title:'Dollar Cliper + BP1 Pen 10 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:140,
        imageURL:'/images/stationary-products/dollar_clipper.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st8',
        title:'Dollar Pointer 10 pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:245,
        imageURL:'/images/stationary-products/dollar_pointer.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st9',
        title:'Dollar Jet Flow Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:355,
        imageURL:'/images/stationary-products/dollar_jet_flow.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st10',
        title:'4 color ball pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/today/4color_ballpen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st11',
        title:"L'il Bin Pencil sharpener 24-pieces",
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:345,
        imageURL:'/images/stationary-products/today/bin_sharpener.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st12',
        title:'China Clay 12-pieces',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:75,
        imageURL:'/images/stationary-products/today/china_clay.jpg',
        mainCategory:'stationary',
        category:'toys',
        section:'',
    },
    {
        id:'st13',
        title:'China Envelope',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:90,
        imageURL:'/images/stationary-products/today/china_envelope.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st14',
        title:'China Fan Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:26,
        imageURL:'/images/stationary-products/today/china_pencil_fan.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st15',
        title:'China Game Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:43,
        imageURL:'/images/stationary-products/today/china_pencil_game.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st16',
        title:'China Whistle Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:26,
        imageURL:'/images/stationary-products/today/china_pencil_whistle.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st17',
        title:'Dux correction pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:525,
        imageURL:'/images/stationary-products/today/dux_correction_pen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st18',
        title:'Dux Stapler D12',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:420,
        imageURL:'/images/stationary-products/today/dux_stapler_d12.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st19',
        title:'Goldfish Colors (Large)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:195,
        imageURL:'/images/stationary-products/today/goldfish_colors_large.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st20',
        title:'Goldfish Colors (small)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/stationary-products/today/goldfish_colors_small.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st21',
        title:'Goldfish Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:185,
        imageURL:'/images/stationary-products/today/goldfish_pencil.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st22',
        title:'Ink Remover',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:230,
        imageURL:'/images/stationary-products/today/ink_remover.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st23',
        title:'Invisible Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:36,
        imageURL:'/images/stationary-products/today/invisible_pen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st24',
        title:'Mercury Fiber Color',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:95,
        imageURL:'/images/stationary-products/today/mercury_fiber_color.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st25',
        title:'Mercury Pencil 8120',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:705,
        imageURL:'/images/stationary-products/today/mercury_pencil.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st26',
        title:'Rocky Sharpener 50 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/stationary-products/today/rocky_sharpener.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st27',
        title:'Sticky Notes',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:72,
        imageURL:'/images/stationary-products/today/sticky_notes.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st28',
        title:'Dux Eraser',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:405,
        imageURL:'/images/stationary-products/dux_eraser.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st29',
        title:'Glue Stick Deer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:430,
        imageURL:'/images/stationary-products/glue_stick_deer.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st30',
        title:'GMSA',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:185,
        imageURL:'/images/stationary-products/gmsa.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st31',
        title:'Mercury Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/stationary-products/mercury_pencil.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st32',
        title:'My Pencil Color 24',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:285,
        imageURL:'/images/stationary-products/my_pencil_color.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st33',
        title:'My Pencil Color 12',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:250,
        imageURL:'/images/stationary-products/my_pencil_color12.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st34',
        title:'Permanent Marker',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:680,
        imageURL:'/images/stationary-products/permanent_marker.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st35',
        title:'Piano Sharpener',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/stationary-products/piano_sharpener.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st36',
        title:'Katoon Sharpener 44 pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/katoon_sharpener.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st37',
        title:'Signature Ball Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:222,
        imageURL:'/images/stationary-products/signature_ball_pen.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st38',
        title:'Stamp Pad',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:600,
        imageURL:'/images/stationary-products/stamp_pad.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st39',
        title:'Steel Scale 12-inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:50,
        imageURL:'/images/stationary-products/steel_scale_12inch.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st40',
        title:'7i7 Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:570,
        imageURL:'/images/stationary-products/tuesday/7i7_ink_pen.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st41',
        title:'Bahadur Eraser',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:100,
        imageURL:'/images/stationary-products/tuesday/bahadur_eraser.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st42',
        title:'Brito Color Large',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:190,
        imageURL:'/images/stationary-products/tuesday/brito_color_large.PNG',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st43',
        title:'Brito Color Small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/stationary-products/tuesday/BritoColorSmall.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st44',
        title:'Protractor (D scale)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:130,
        imageURL:'/images/stationary-products/tuesday/protractor.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st45',
        title:'Deer Wonder Pencil',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:170,
        imageURL:'/images/stationary-products/tuesday/DeerWonderPencil.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st46',
        title:'Dollar Ink 12 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:400,
        imageURL:'/images/stationary-products/tuesday/dollar_ink.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st47',
        title:'Highlighter Neon',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:850,
        imageURL:'/images/stationary-products/tuesday/highlighter_neon.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st48',
        title:'Murcury Urdu Marker',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:95,
        imageURL:'/images/stationary-products/tuesday/MurcuryUrduMarker.jpeg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st49',
        title:'Tape Osaka',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:425,
        imageURL:'/images/stationary-products/tuesday/OSAKATape.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st50',
        title:'Piano A-star Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:430,
        imageURL:'/images/stationary-products/tuesday/piano_A_star_pen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st51',
        title:'Piano Fountain Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/tuesday/piano_fountain_ink_pen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st52',
        title:'Piano G5 Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:110,
        imageURL:'/images/stationary-products/tuesday/piano_g5.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st53',
        title:'Piano Pointer',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:205,
        imageURL:'/images/stationary-products/tuesday/PianoPointer.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st54',
        title:'Scotch Tape 1 inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/tuesday/scotch_tap_1inch.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st55',
        title:'Scotch Tape 2 inch',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/tuesday/scotch_tap_2inch.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st56',
        title:'Scotch Tape small',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:70,
        imageURL:'/images/stationary-products/tuesday/scotch_tap_rs10.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st57',
        title:'SP-10 Ink Pen',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:510,
        imageURL:'/images/stationary-products/tuesday/sp10_ink_pen.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st58',
        title:'Staple Pin Dollar #10',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:440,
        imageURL:'/images/stationary-products/tuesday/staple_pin_dollar_10.jpg',
        mainCategory:'stationary',
        category:'school-office',
        brand:'dollar',
        section:'',
    },
    {
        id:'st59',
        title:'Staple Pin Dux #10',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:0,
        imageURL:'/images/stationary-products/tuesday/staple_pin_dux_10.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st60',
        title:'TipTop Glue',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:245,
        imageURL:'/images/stationary-products/tuesday/tip_top_glue.png',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st61',
        title:'UHU',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:415,
        imageURL:'/images/stationary-products/tuesday/UHU.jpg',
        mainCategory:'stationary',
        category:'school-office',
        section:'',
    },
    {
        id:'st62',
        title:'Party Balloon 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:320,
        imageURL:'/images/stationary-products/wednesday/party_baloon.jpg',
        mainCategory:'stationary',
        category:'decoration',
        section:'',
    },
    {
        id:'st62a',
        title:'Party Balloon 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:550,
        imageURL:'/images/stationary-products/wednesday/party_balloons2.png',
        mainCategory:'stationary',
        category:'',
        section:'',
    },
    {
        id:'st63',
        title:'Birthday Balloons 100 Pcs',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:300,
        imageURL:'/images/stationary-products/wednesday/ballons_100pcs.jpg',
        mainCategory:'stationary',
        category:'decoration',
        section:'',
    },
    {
        id:'st64',
        title:'Sim Sim Ball (Small)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:200,
        imageURL:'/images/stationary-products/sim_sim_ball.jpg',
        mainCategory:'stationary',
        category:'toys',
        section:'',
    },
    {
        id:'st65',
        title:'Sim Sim Ball (Medium)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:250,
        imageURL:'/images/stationary-products/sim_sim_ball.jpg',
        mainCategory:'stationary',
        category:'toys',
        section:'',
    },
    {
        id:'st66',
        title:'Sim Sim Ball (Large)',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        price:450,
        imageURL:'/images/stationary-products/sim_sim_ball.jpg',
        mainCategory:'stationary',
        category:'toys',
        section:'',
    },

]

export const FoodProducts = [
    {

    }
]

export const StationaryProducts = [
    {

    }
]